//
//  RuleSetContextTests.swift
//  Harmonize
//
//  Copyright (c) Perry Street Software 2026. All Rights Reserved.
//

import Foundation
import Harmonize
import XCTest

final class RuleSetContextTests: XCTestCase {
    private enum SingleRule: RuleSet {
        static let rules: [Rule] = [
            Rule(
                id: "viewmodels-inherit-base",
                summary: "Every ViewModel must inherit from BaseViewModel.",
                why: "BaseViewModel owns subscription cancellation.",
                howToFix: "Declare the type as `final class MyViewModel: BaseViewModel`.",
                badExample: "final class ProfileViewModel {}",
                goodExample: "final class ProfileViewModel: BaseViewModel {}"
            ) { scope in
                scope.classes().withNameEndingWith("ViewModel").assertTrue { $0.inherits(from: "BaseViewModel") }
            }
        ]
    }

    // MARK: - Rendering

    func testMarkdownContextRendersARuleInFull() {
        let markdown = SingleRule.markdownContext(intro: "Follow these.")

        XCTAssertEqual(markdown, """
        <!-- Generated by Harmonize. Do not edit by hand: edit the rules and regenerate. -->

        # Architecture Rules

        Follow these.

        ## Every ViewModel must inherit from BaseViewModel.

        `viewmodels-inherit-base`

        BaseViewModel owns subscription cancellation.

        **How to fix:** Declare the type as `final class MyViewModel: BaseViewModel`.

        **❌ Bad:**

        ```swift
        final class ProfileViewModel {}
        ```

        **✅ Good:**

        ```swift
        final class ProfileViewModel: BaseViewModel {}
        ```

        """)
    }

    func testMarkdownContextUsesTheGivenTitle() {
        let markdown = SingleRule.markdownContext(title: "How We Build Things")
        XCTAssertTrue(markdown.contains("# How We Build Things"))
    }

    func testMarkdownContextIncludesTheDefaultPreambleByDefault() {
        XCTAssertTrue(SingleRule.markdownContext().contains(SingleRule.defaultIntro))
    }

    func testMarkdownContextPreservesDeclarationOrder() {
        let markdown = DemoRules.markdownContext()
        let positions = DemoRules.rules.map { markdown.range(of: "`\($0.id)`")?.lowerBound }

        XCTAssertFalse(positions.contains(where: { $0 == nil }), "Every rule must render a section.")
        XCTAssertEqual(positions.compactMap { $0 }, positions.compactMap { $0 }.sorted())
    }

    func testWarningSeverityIsCalledOutButErrorIsNot() {
        enum Warned: RuleSet {
            static let rules: [Rule] = [
                Rule(id: "soft-rule", severity: .warning, why: "Prefer this.") { _ in },
                Rule(id: "hard-rule", severity: .error, why: "Require this.") { _ in }
            ]
        }

        let markdown = Warned.markdownContext()
        XCTAssertTrue(markdown.contains("**Severity:** warning"))
        XCTAssertEqual(markdown.components(separatedBy: "**Severity:**").count - 1, 1)
    }

    func testRulesWithoutExamplesRenderWithoutCodeFences() {
        enum Bare: RuleSet {
            static let rules: [Rule] = [Rule(id: "bare-rule", why: "Because.") { _ in }]
        }

        let markdown = Bare.markdownContext()
        XCTAssertTrue(markdown.contains("## bare-rule"))
        XCTAssertFalse(markdown.contains("```swift"))
    }

    // MARK: - Drift detection

    func testWriteContextThenAssertUpToDateSucceeds() throws {
        let path = "\(Self.generatedDirectory)/AGENTS.md"
        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }

        let reporter = CollectingReporter()
        HarmonizeReporting.withReporter(reporter) {
            SingleRule.assertContextIsUpToDate(at: path)
        }

        XCTAssertTrue(reporter.isEmpty)
    }

    func testAssertUpToDateReportsWhenTheCatalogHasChanged() throws {
        let path = "\(Self.generatedDirectory)/AGENTS.md"
        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }

        let reporter = CollectingReporter()
        HarmonizeReporting.withReporter(reporter) {
            DemoRules.assertContextIsUpToDate(at: path)
        }

        XCTAssertEqual(reporter.failures.count, 1)
        XCTAssertTrue(reporter.failures[0].message.contains("out of date"))
    }

    func testAssertUpToDateReportsWhenTheFileIsMissing() {
        let reporter = CollectingReporter()
        HarmonizeReporting.withReporter(reporter) {
            SingleRule.assertContextIsUpToDate(at: "\(Self.generatedDirectory)/DoesNotExist.md")
        }

        XCTAssertEqual(reporter.failures.count, 1)
        XCTAssertTrue(reporter.failures[0].message.contains("missing"))
    }

    func testWriteContextCreatesIntermediateDirectories() throws {
        let url = try SingleRule.writeContext(to: "\(Self.generatedDirectory)/nested/deeper/AGENTS.md")
        defer { removeGeneratedDirectory(containing: url) }

        XCTAssertTrue(FileManager.default.fileExists(atPath: url.path))
        XCTAssertEqual(try String(contentsOf: url, encoding: .utf8), SingleRule.markdownBlock() + "\n")
    }

    func testSyncContextVerifiesWhenTheUpdateFlagIsUnset() throws {
        let path = "\(Self.generatedDirectory)/AGENTS.md"
        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }

        XCTAssertNil(
            ProcessInfo.processInfo.environment[SingleRule.updateContextEnvironmentKey],
            "This test asserts the default, verifying behavior."
        )

        let reporter = CollectingReporter()
        HarmonizeReporting.withReporter(reporter) {
            DemoRules.syncContext(at: path)
        }

        XCTAssertEqual(reporter.failures.count, 1)
        XCTAssertTrue(reporter.failures[0].message.contains("out of date"))
        XCTAssertEqual(
            try String(contentsOf: url, encoding: .utf8),
            SingleRule.markdownBlock() + "\n",
            "Verification must not rewrite the file."
        )
    }

    // MARK: - Markers

    func testWriteContextAppendsToAFileItDoesNotOwn() throws {
        let path = "\(Self.generatedDirectory)/CLAUDE.md"
        let handWritten = """
        # CLAUDE.md

        Run the tests with `swift test`.
        """

        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }
        try handWritten.write(to: url, atomically: true, encoding: .utf8)
        try SingleRule.writeContext(to: path)

        let contents = try String(contentsOf: url, encoding: .utf8)
        XCTAssertTrue(contents.hasPrefix(handWritten))
        XCTAssertTrue(contents.contains(SingleRule.markdownBlock()))
    }

    func testWriteContextReplacesOnlyTheGeneratedBlock() throws {
        let path = "\(Self.generatedDirectory)/CLAUDE.md"
        let before = "# CLAUDE.md\n\nRun the tests with `swift test`.\n"
        let after = "\n## Release process\n\nTag and push.\n"

        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }
        try (before + SingleRule.markdownBlock() + after).write(to: url, atomically: true, encoding: .utf8)

        // A different catalog rewrites the block and leaves the hand written text alone.
        try DemoRules.writeContext(to: path)

        let contents = try String(contentsOf: url, encoding: .utf8)
        XCTAssertEqual(contents, before + DemoRules.markdownBlock() + after)
    }

    func testAssertUpToDateIgnoresChangesOutsideTheBlock() throws {
        let path = "\(Self.generatedDirectory)/CLAUDE.md"
        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }

        let edited = "Hand written intro.\n\n" + SingleRule.markdownBlock() + "\n\nHand written outro.\n"
        try edited.write(to: url, atomically: true, encoding: .utf8)

        let reporter = CollectingReporter()
        HarmonizeReporting.withReporter(reporter) {
            SingleRule.assertContextIsUpToDate(at: path)
        }

        XCTAssertTrue(reporter.isEmpty)
    }

    func testAssertUpToDateReportsWhenTheFileHasNoMarkers() throws {
        let path = "\(Self.generatedDirectory)/CLAUDE.md"
        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }
        try "# CLAUDE.md\n".write(to: url, atomically: true, encoding: .utf8)

        let reporter = CollectingReporter()
        HarmonizeReporting.withReporter(reporter) {
            SingleRule.assertContextIsUpToDate(at: path)
        }

        XCTAssertEqual(reporter.failures.count, 1)
        XCTAssertTrue(reporter.failures[0].message.contains("no Harmonize markers"))
    }

    func testAssertUpToDateReportsAnUnpairedMarker() throws {
        let path = "\(Self.generatedDirectory)/CLAUDE.md"
        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }
        try "\(SingleRule.contextStartMarker)\nrules\n".write(to: url, atomically: true, encoding: .utf8)

        let reporter = CollectingReporter()
        HarmonizeReporting.withReporter(reporter) {
            SingleRule.assertContextIsUpToDate(at: path)
        }

        XCTAssertEqual(reporter.failures.count, 1)
        XCTAssertTrue(reporter.failures[0].message.contains("not its pair"))
    }

    func testWriteContextThrowsOnRepeatedMarkers() throws {
        let path = "\(Self.generatedDirectory)/CLAUDE.md"
        let url = try SingleRule.writeContext(to: path)
        defer { removeGeneratedDirectory(containing: url) }
        try (SingleRule.markdownBlock() + "\n" + SingleRule.markdownBlock())
            .write(to: url, atomically: true, encoding: .utf8)

        XCTAssertThrowsError(try SingleRule.writeContext(to: path)) { error in
            XCTAssertEqual(error as? ContextError, .repeatedMarkers(path: path))
        }
    }

    // MARK: - Helpers

    private static let generatedDirectory = ".harmonize-generated-tests"

    private func removeGeneratedDirectory(containing url: URL) {
        var directory = url

        while directory.lastPathComponent != Self.generatedDirectory && directory.path != "/" {
            directory = directory.deletingLastPathComponent()
        }

        guard directory.lastPathComponent == Self.generatedDirectory else { return }
        try? FileManager.default.removeItem(at: directory)
    }
}
