//
//  RuleSet+Context.swift
//  Harmonize
//
//  Copyright 2026 Perry Street Software Inc.

//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at

//  http://www.apache.org/licenses/LICENSE-2.0

//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation

/// Writes a ``RuleSet`` as the instructions an AI agent reads before writing code.
///
/// Files like `CLAUDE.md` or `AGENTS.md` are written by hand and nothing checks them, so they
/// get out of date as the codebase grows. Generating them from your rules keeps both in sync,
/// and ``assertContextIsUpToDate(at:title:intro:fileID:file:line:column:)`` fails once they
/// don't match.
///
/// The generated Markdown is written between `<!-- harmonize:start -->` and
/// `<!-- harmonize:end -->`, so it can go into a file you already maintain by hand. Only the
/// text between the markers is written and compared, everything around it is left alone.
public extension RuleSet {
    static var contextStartMarker: String { "<!-- harmonize:start -->" }

    static var contextEndMarker: String { "<!-- harmonize:end -->" }

    static var defaultIntro: String {
        """
        These are the architectural rules for this codebase. Harmonize runs them \
        as tests in CI, so code that breaks one fails the build.

        They are not suggestions. If a rule gets in the way of what you were asked \
        to do, follow the rule and say so instead of working around it.
        """
    }

    /// Returns the rules as Markdown.
    ///
    /// - parameters:
    ///   - title: The document's top level heading.
    ///   - intro: The text written above the rules. ``defaultIntro`` when not provided.
    /// - returns: The Markdown document, ending in a newline.
    static func markdownContext(
        title: String = "Architecture Rules",
        intro: String? = nil
    ) -> String {
        var sections: [String] = [
            "<!-- Generated by Harmonize. Do not edit by hand: edit the rules and regenerate. -->",
            "# \(title)",
            intro ?? defaultIntro
        ]

        sections.append(contentsOf: rules.map(\.markdownSection))

        return sections.joined(separator: "\n\n") + "\n"
    }

    /// Returns the rules as Markdown, written between the Harmonize markers.
    ///
    /// This is what gets written to and compared within a file. It does not end in a newline.
    static func markdownBlock(
        title: String = "Architecture Rules",
        intro: String? = nil
    ) -> String {
        "\(contextStartMarker)\n\(markdownContext(title: title, intro: intro))\(contextEndMarker)"
    }

    /// The environment variable that switches
    /// ``syncContext(at:title:intro:fileID:file:line:column:)`` from verifying to writing.
    static var updateContextEnvironmentKey: String { "HARMONIZE_UPDATE_CONTEXT" }

    /// Writes the generated context when `HARMONIZE_UPDATE_CONTEXT` is set, otherwise asserts
    /// the file is up to date.
    ///
    /// ```swift
    /// func testAgentInstructions() {
    ///     AppRules.syncContext(at: "AGENTS.md")
    /// }
    /// ```
    ///
    /// ```bash
    /// HARMONIZE_UPDATE_CONTEXT=1 swift test --filter testAgentInstructions
    /// ```
    static func syncContext(
        at path: String,
        title: String = "Architecture Rules",
        intro: String? = nil,
        fileID: StaticString = #fileID,
        file: StaticString = #filePath,
        line: UInt = #line,
        column: UInt = #column
    ) {
        guard shouldUpdateContext else {
            assertContextIsUpToDate(
                at: path,
                title: title,
                intro: intro,
                fileID: fileID,
                file: file,
                line: line,
                column: column
            )
            return
        }

        do {
            try writeContext(to: path, title: title, intro: intro, file)
        } catch {
            reportInline(
                message: "Unable to write generated context to '\(path)': \(error).",
                fileID: fileID,
                file: file,
                line: line,
                column: column
            )
        }
    }

    /// Writes the generated Markdown to the given path, relative to the project root.
    ///
    /// When the file already contains the Harmonize markers only the text between them is
    /// replaced. When it exists without them the generated block is appended, and when it
    /// doesn't exist it is created. Intermediate directories are created when needed.
    ///
    /// - parameter file: The call site, used to resolve the project root.
    /// - returns: The URL written to.
    @discardableResult
    static func writeContext(
        to path: String,
        title: String = "Architecture Rules",
        intro: String? = nil,
        _ file: StaticString = #file
    ) throws -> URL {
        let url = try contextURL(for: path, file: file)
        let block = markdownBlock(title: title, intro: intro)
        let contents: String

        if let existing = try? String(contentsOf: url, encoding: .utf8) {
            if let range = try markerRange(in: existing, path: path) {
                contents = existing.replacingCharacters(in: range, with: block)
            } else {
                let separator = existing.hasSuffix("\n") ? "\n" : "\n\n"
                contents = existing + separator + block + "\n"
            }
        } else {
            contents = block + "\n"
        }

        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        try contents.write(to: url, atomically: true, encoding: .utf8)

        return url
    }

    /// Asserts that the generated block in the file at the given path matches what your rules
    /// generate today.
    ///
    /// - parameters:
    ///   - path: Path to the file, relative to the project root.
    ///   - title: Must match the title used to generate the file.
    ///   - intro: Must match the intro used to generate the file.
    static func assertContextIsUpToDate(
        at path: String,
        title: String = "Architecture Rules",
        intro: String? = nil,
        fileID: StaticString = #fileID,
        file: StaticString = #filePath,
        line: UInt = #line,
        column: UInt = #column
    ) {
        let regenerate = "Regenerate it with `\(Self.self).writeContext(to: \"\(path)\")`."

        let url: URL
        do {
            url = try contextURL(for: path, file: file)
        } catch {
            reportInline(
                message: "Unable to resolve '\(path)' from the project root: \(error).",
                fileID: fileID,
                file: file,
                line: line,
                column: column
            )
            return
        }

        guard let existing = try? String(contentsOf: url, encoding: .utf8) else {
            reportInline(
                message: "Generated context is missing at '\(path)'. \(regenerate)",
                fileID: fileID,
                file: file,
                line: line,
                column: column
            )
            return
        }

        let range: Range<String.Index>?
        do {
            range = try markerRange(in: existing, path: path)
        } catch {
            reportInline(
                message: "\(error)",
                fileID: fileID,
                file: file,
                line: line,
                column: column
            )
            return
        }

        guard let range else {
            reportInline(
                message: """
                '\(path)' has no Harmonize markers, so it holds no generated context. \(regenerate)
                """,
                fileID: fileID,
                file: file,
                line: line,
                column: column
            )
            return
        }

        guard String(existing[range]) != markdownBlock(title: title, intro: intro) else { return }

        reportInline(
            message: """
            Generated context at '\(path)' is out of date, your rules have changed since \
            it was written and the instructions your agents read no longer match the rules CI \
            enforces. \(regenerate)
            """,
            fileID: fileID,
            file: file,
            line: line,
            column: column
        )
    }

    private static var shouldUpdateContext: Bool {
        guard let value = ProcessInfo.processInfo.environment[updateContextEnvironmentKey] else {
            return false
        }
        return !["", "0", "false", "NO"].contains(value)
    }

    private static func contextURL(for path: String, file: StaticString) throws -> URL {
        try ResolveProjectWorkingDirectory()(file)
            .appendingPathComponent(path)
            .standardized
    }

    /// The range covering both markers and everything between them, or nil when the text has
    /// neither.
    private static func markerRange(in text: String, path: String) throws -> Range<String.Index>? {
        let start = text.range(of: contextStartMarker)
        let end = text.range(of: contextEndMarker)

        switch (start, end) {
        case (nil, nil):
            return nil
        case (.some(let start), .some(let end)):
            guard start.upperBound <= end.lowerBound else {
                throw ContextError.markersOutOfOrder(path: path)
            }
            guard text.range(of: contextStartMarker, range: start.upperBound..<text.endIndex) == nil,
                  text.range(of: contextEndMarker, range: end.upperBound..<text.endIndex) == nil
            else {
                throw ContextError.repeatedMarkers(path: path)
            }
            return start.lowerBound..<end.upperBound
        case (.some, nil):
            throw ContextError.missingMarker(path: path, marker: contextEndMarker)
        case (nil, .some):
            throw ContextError.missingMarker(path: path, marker: contextStartMarker)
        }
    }
}

// MARK: - ContextError

public enum ContextError: Error, Equatable, CustomStringConvertible {
    case missingMarker(path: String, marker: String)
    case markersOutOfOrder(path: String)
    case repeatedMarkers(path: String)

    public var description: String {
        switch self {
        case let .missingMarker(path, marker):
            "'\(path)' has one Harmonize marker but not its pair, '\(marker)' is missing."
        case let .markersOutOfOrder(path):
            "'\(path)' has its Harmonize end marker before the start one."
        case let .repeatedMarkers(path):
            "'\(path)' has more than one pair of Harmonize markers, so it can't tell which block to write."
        }
    }
}

// MARK: - Rendering

private extension Rule {
    var markdownSection: String {
        var lines = ["## \(summary?.trimmed.nilIfBlank ?? id)"]

        if summary?.trimmed.nilIfBlank != nil {
            lines.append("`\(id)`")
        }

        if let why = why?.trimmed.nilIfBlank {
            lines.append(why)
        }

        if let howToFix = howToFix?.trimmed.nilIfBlank {
            lines.append("**How to fix:** \(howToFix)")
        }

        if severity == .warning {
            lines.append("**Severity:** warning, violations are reported but do not fail the build.")
        }

        if let examples {
            lines.append("**❌ Bad:**")
            lines.append(examples.badExample.swiftCodeFence)
            lines.append("**✅ Good:**")
            lines.append(examples.goodExample.swiftCodeFence)
        }

        return lines.joined(separator: "\n\n")
    }
}

private extension String {
    var trimmed: String {
        trimmingCharacters(in: .whitespacesAndNewlines)
    }

    var nilIfBlank: String? {
        isEmpty ? nil : self
    }

    var swiftCodeFence: String {
        "```swift\n\(trimmed)\n```"
    }
}
